# Generated by Django 3.1.2 on 2020-11-26 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Cinema_hall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.IntegerField()),
                ('use_3d', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id_film', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45)),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemaHall_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Pegi',
            fields=[
                ('id_pegi', models.AutoField(primary_key=True, serialize=False)),
                ('age_range', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_options',
            fields=[
                ('id_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('name_ticket', models.CharField(max_length=45)),
                ('price', models.CharField(max_length=45)),
                ('number_of_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transalation',
            fields=[
                ('id_translation', models.AutoField(primary_key=True, serialize=False)),
                ('name_translation', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=45)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id_seat', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('its_fill', models.SmallIntegerField()),
                ('id_cinema_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemaHall_app.cinema_hall')),
            ],
        ),
        migrations.CreateModel(
            name='Give_me_seat',
            fields=[
                ('id_give_me_seat', models.AutoField(primary_key=True, serialize=False)),
                ('id_seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemaHall_app.seats')),
                ('id_ticket_options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemaHall_app.ticket_options')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemaHall_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Film_shows',
            fields=[
                ('id_film_shows', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('id_CinemaHall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemaHall_app.cinema_hall')),
                ('id_Translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemaHall_app.transalation')),
                ('id_film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemaHall_app.film')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='id_pegi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemaHall_app.pegi'),
        ),
    ]
